import { InternalFacts } from '../internal/Presentation'
import { Dialog, DisplayDate, StatusBadge } from '../design/foundation'
﻿import { useState } from 'react'
import type { View } from '../App'
import { useAccess } from '../access/AccessContext'
import { hasPermission } from '../access/authorization'
import { InternalDenied, InternalNavigation } from '../access/InternalNavigation'
import { useGroups } from '../groups/GroupContext'
import { businessClock } from '../settings/service'
import { processDefinition, failed, needsAttention, type Run } from './model'
import { readRuns, type ProcessPreview } from './service'
const panel='bg-white border border-slate-200 rounded-xl p-5 space-y-3'
const button='bg-[#10243A] text-white rounded-lg px-4 py-2 disabled:opacity-40'
export function RunDetail({run,runs}:{run:Run;runs:readonly Run[]}){
 return <section className={panel}><h2 className="text-xl font-semibold">Run detail</h2><p>{run.definition.name} · {run.id}</p><StatusBadge status={run.status}/><p>Business Date: {run.businessDate} · {run.mode} · {run.environment}</p><p>Initiated by {run.actor.name} · {run.trigger} · {run.reason}</p><p>Actual start: <DisplayDate value={run.startedAt}/> · Actual end: <DisplayDate value={run.completedAt}/></p><InternalFacts items={[{label:"Evaluated",value:run.evaluated},{label:"Changed",value:run.changed},{label:"Skipped / no-op",value:run.skipped},{label:"Failed",value:run.failed}]}/><p className="text-sm text-slate-600">Counts represent Group or financial-world evaluations per step, not money or unique Members. Reference-clock-only updates do not count as financial changes.</p>{run.retryOf&&<p>Retry of: {run.retryOf}</p>}<p>Linked retries: {runs.filter(r=>r.retryOf===run.id).map(r=>r.id+' ('+r.status+')').join(', ')||'None'}</p>{run.steps.map(s=><article key={s.key} className="border rounded-lg p-4"><h3 className="font-semibold">{s.name} · {s.status}</h3><p><DisplayDate value={s.startedAt}/> → <DisplayDate value={s.completedAt}/></p><p>Evaluated {s.evaluated} · Changed {s.changed} · Skipped / no-op {s.skipped} · Failed {s.failed}</p>{s.errors.map(e=><p key={e} className="text-red-800">{e}</p>)}{s.notes.map((n,i)=><p key={i}>{n}</p>)}</article>)}</section>
}
export function ProcessConfirmation({preview,confirm,cancel}:{preview:ProcessPreview;confirm:()=>void;cancel:()=>void}){
 return <Dialog label="Lifecycle run confirmation" onClose={cancel}><div className="space-y-3"><h2 className="text-xl font-semibold">Confirm lifecycle evaluation</h2><p>{preview.businessDate} · {preview.mode} · {preview.environment}</p><p>Reason: {preview.reason}</p><p>Potential Group evaluations: {preview.eligibleGroups} · Isolated/excluded: {preview.isolatedGroups}</p><p>{preview.catchUp?'Catch-up evaluation through this date may be required.':'A same-date rerun may evaluate newly eligible data.'}</p><ol className="list-decimal pl-5">{processDefinition.steps.map(s=><li key={s.key}>{s.name}</li>)}</ol>{preview.retryOf&&<p>New retry run for {preview.retryOf}; original business context is retained.</p>}{preview.warnings.map(w=><p key={w}>{w}</p>)}<button className={button} onClick={confirm}>Confirm and execute</button> <button className="border rounded-lg px-4 py-2" onClick={cancel}>Cancel</button></div></Dialog>
}
export function ScheduledProcessesWorkspace({navigate}:{navigate:(v:View)=>void}){
 const a=useAccess()
 if(!hasPermission(a.session,'operations.process.view'))return <InternalDenied navigate={navigate} module="Scheduled Processes"/>
 return <><InternalNavigation navigate={navigate} current="scheduled-processes" /><ProcessBody key={a.session!.personaId}/></>
}
export function ProcessBody(){
 const a=useAccess(),g=useGroups(),[reason,setReason]=useState(''),[preview,setPreview]=useState<ProcessPreview|null>(null),[selected,select]=useState(''),[error,setError]=useState(''),[onlyFailed,setOnlyFailed]=useState(false),[,refresh]=useState(0)
 const runs=readRuns(a.session),clock=businessClock(),run=runs.find(r=>r.id===selected),attention=runs.filter(r=>needsAttention(r,runs)),canRun=hasPermission(a.session,'operations.process.run'),canRetry=hasPermission(a.session,'operations.process.retry')
 const propose=(retryOf?:string)=>{try{setPreview(g.processPreview(a.currentSession(),reason,retryOf));setError('')}catch(e){setError((e as Error).message)}}
 const execute=()=>{try{const result=g.processExecute(a.currentSession(),preview!);select(result.id);setPreview(null);setReason('');setError('Run recorded: '+result.status);refresh(v=>v+1)}catch(e){setError((e as Error).message);setPreview(null)}}
 return <main id="internal-main" tabIndex={-1} className="max-w-6xl mx-auto p-6 space-y-5"><h1 className="text-2xl font-bold">Operations · Scheduled Processes</h1><p>Business Date: {clock.businessDate} · {clock.mode} · {clock.environment}</p><p>Manual, synchronous UAT evaluation. Changing Business Date does not execute lifecycle processing.</p>{error&&<p role="status" className="border rounded-lg p-3 bg-amber-50">{error}</p>}<section className={panel}><h2 className="text-xl font-semibold">Process catalogue</h2><h3 className="font-semibold">{processDefinition.name}</h3><p>{processDefinition.description}</p><p className="text-sm">{processDefinition.key} · {processDefinition.domain} · Financial: Yes · Safe to retry: Yes · {processDefinition.availability}</p><details><summary className="font-semibold">Evaluation steps</summary><ol className="space-y-3 mt-3">{processDefinition.steps.map(s=><li key={s.key}><strong>{s.order}. {s.name}</strong><p>{s.description}</p></li>)}</ol></details><p>Latest run: {runs.at(-1)?.status||'No runs recorded'} · {runs.at(-1)?.completedAt ? <DisplayDate value={runs.at(-1)?.completedAt}/> : 'Not yet evaluated'}</p><p className="text-sm text-slate-600">Daily penalty accrual and Post-Payout Default use the accepted Group rate and approved seven-day threshold. Recovery payments and Cycle completion remain explicit domain actions.</p>{(canRun||canRetry)&&clock.environment!=='Production'&&<><label className="block">Reason for manual run or retry<textarea aria-label="Process reason" className="border rounded-lg p-2 block w-full mt-1" value={reason} onChange={e=>setReason(e.target.value)}/></label>{canRun&&<button className={button} onClick={()=>propose()}>Preview lifecycle run</button>}</>}</section>
 <section className={panel}><h2 className="text-xl font-semibold">Failed / incomplete runs</h2>{!attention.length?<p>No failed runs require attention.</p>:attention.map(r=><article key={r.id} className="border rounded-lg p-3"><p>{r.id} · {r.status} · {r.businessDate}</p><button className="underline mr-4" onClick={()=>select(r.id)}>Inspect failure</button>{canRetry&&clock.environment!=='Production'&&<button className="border border-amber-600 rounded-lg px-3 py-1" onClick={()=>propose(r.id)}>Preview retry</button>}</article>)}</section>
 {preview&&<ProcessConfirmation preview={preview} confirm={execute} cancel={()=>setPreview(null)}/>}
 <section className={panel}><h2 className="text-xl font-semibold">Run history</h2><label><input type="checkbox" checked={onlyFailed} onChange={e=>setOnlyFailed(e.target.checked)}/> Failed / partial only</label>{!runs.length&&<p>No process runs have been recorded yet.</p>}{[...runs].reverse().filter(r=>!onlyFailed||failed(r)).map(r=><button className="block text-left w-full border rounded-lg p-3" key={r.id} onClick={()=>select(r.id)}>{r.businessDate} · {r.status} · {r.actor.name} · <DisplayDate value={r.startedAt}/><span className="block text-xs">{r.id}{r.retryOf?' · Retry of '+r.retryOf:''}</span></button>)}</section>{run&&<RunDetail run={run} runs={runs}/>}</main>
}
