import test from 'node:test'
import assert from 'node:assert/strict'
import { seedPersona } from '../src/clients/seeds.ts'
import { seedOrganization } from '../src/organizations/seeds.ts'
import { seedSession } from '../src/access/seeds.ts'
import { roundDemo } from '../src/rounds/seeds.ts'
import { payoutDemo } from '../src/payouts/seeds.ts'
import { cycleOf, exampleFeeBoundary, transition, memberTerms, accepted } from '../src/groups/model.ts'
import { seedGroup } from '../src/groups/seeds.ts'
import { advanceReference } from '../src/rounds/service.ts'
import { balances } from '../src/rounds/model.ts'
import { emptyPayments } from '../src/payments/model.ts'
import { emptyLifecycle } from '../src/lifecycle/model.ts'
import { recoveryBalances } from '../src/lifecycle/recovery.ts'
import { resolveRecovery } from '../src/lifecycle/continuation.ts'
import { accruePenalties, evaluatePostPayoutDefaults, waivePenalty } from '../src/penalties/service.ts'
import { dailyPenalty, validatePenaltyRate } from '../src/penalties/policy.ts'
import { penaltyBalance } from '../src/penalties/balances.ts'
import { allocateRecovery } from '../src/reports/recoveryAllocation.ts'
import { generateReport } from '../src/reports/service.ts'
import { generateInternalReport } from '../src/reports/internalService.ts'
import { createSettings } from '../src/settings/service.ts'
import { createProcessState } from '../src/processes/model.ts'
import { previewProcess, executeProcess } from '../src/processes/service.ts'
const actual='2026-09-17T12:00:00.000Z'
const plus=(at,days)=>new Date(Date.parse(at)+days*86400000).toISOString()
const org=()=>seedOrganization(seedPersona('verified'),'active')
function fixture(frequency='Monthly') {
 const organization=org();let g=roundDemo(organization,'penalty-fixture',exampleFeeBoundary(),frequency,'Upcoming')
 const c=cycleOf(g);c.terms.dailyPenaltyRateBps=5;c.snapshot.terms.dailyPenaltyRateBps=5
 const late=c.active.rounds[0].schedule.lateAt
 g=advanceReference(g,late)
 const obligation=cycleOf(g).active.obligations.find(o=>o.memberId!==organization.ownerMemberId&&balances(o).required===10000000)
 return {g,organization,late,id:obligation.id,memberId:obligation.memberId}
}
function pay(g,id,amount,at){
 const c=cycleOf(g),o=c.active.obligations.find(o=>o.id===id),p=g.payments??=emptyPayments();let left=amount
 for(const part of o.components){const amountMinor=Math.min(left,part.requiredMinor-part.requiredSatisfiedMinor);if(!amountMinor)continue;left-=amountMinor;part.requiredSatisfiedMinor+=amountMinor;p.allocations.push({id:'allocation-'+p.allocations.length,transactionId:'test-receipt-'+p.allocations.length,organizationId:g.organizationId,groupId:g.id,cycleId:c.id,roundId:o.roundId,memberId:o.memberId,obligationId:o.id,componentId:part.id,kind:'required',amountMinor,confirmedAt:at,businessAt:at,timeliness:'late'})}
 assert.equal(left,0)
}
function received(g,memberId,at){(g.lifecycle??=emptyLifecycle()).payoutFacts.push({cycleId:cycleOf(g).id,position:2,memberId,status:'received-recorded',entitlementMinor:40000000,at})}
const charges=(g,id)=>g.penalties?.accruals.filter(a=>!id||a.obligationId===id)||[]
const sum=g=>charges(g).reduce((n,a)=>n+a.amountMinor,0)
function evaluated(f,at=plus(f.late,7)){received(f.g,f.memberId,f.late);f.g=advanceReference(f.g,at);return evaluatePostPayoutDefaults(accruePenalties(f.g,at,actual),at,actual)}
for(const offset of [-1,-0.1])test('no accrual before grace expires '+offset,()=>{const f=fixture();assert.equal(sum(accruePenalties(f.g,plus(f.late,offset),actual)),0)})
test('first eligible local day, integer kobo half-up and simple non-compounding',()=>{const f=fixture(),g=accruePenalties(f.g,plus(f.late,2),actual);assert.equal(charges(g,f.id).length,3);assert.deepEqual(charges(g,f.id).map(a=>a.amountMinor),[5000,5000,5000]);assert.ok(charges(g).every(a=>a.dailyRateBps===5&&a.recordedAt===actual));assert.equal(dailyPenalty(1000,5),1);assert.equal(dailyPenalty(999,5),0)})
test('partial payments change future day basis and preserve prior postings',()=>{const f=fixture();let g=accruePenalties(f.g,f.late,actual);const original=structuredClone(g.penalties.accruals);pay(g,f.id,4000000,plus(f.late,0.5));g=accruePenalties(g,plus(f.late,2),actual);assert.deepEqual(charges(g,f.id).map(a=>a.amountMinor),[5000,3000,3000]);for(const a of original)assert.deepEqual(g.penalties.accruals.find(x=>x.id===a.id),a)})
test('catch-up reconstructs dated partial principal instead of charging current balance on all days',()=>{const f=fixture();pay(f.g,f.id,4000000,plus(f.late,1.5));const g=accruePenalties(f.g,plus(f.late,3),actual);assert.deepEqual(charges(g,f.id).map(a=>a.principalBasisMinor),[10000000,10000000,6000000,6000000])})
test('full principal payment stops accrual; penalty alone does not compound',()=>{const f=fixture();let g=accruePenalties(f.g,f.late,actual);pay(g,f.id,10000000,plus(f.late,0.5));g=accruePenalties(g,plus(f.late,4),actual);assert.equal(charges(g,f.id).length,1);assert.equal(penaltyBalance(g,charges(g,f.id)[0]).outstanding,5000)})
test('principal cleared before first accrual incurs no penalty',()=>{const f=fixture();pay(f.g,f.id,10000000,plus(f.late,-0.5));assert.equal(charges(accruePenalties(f.g,plus(f.late,4),actual),f.id).length,0)})
test('optional own-position skip excluded; other holdings and halves remain required',()=>{const f=fixture(),g=accruePenalties(f.g,f.late,actual),c=cycleOf(g),ownerObligation=c.active.obligations.find(o=>o.memberId===f.organization.ownerMemberId);assert.equal(charges(g,ownerObligation.id).length,1);assert.equal(charges(g,ownerObligation.id)[0].position,3);assert.equal(charges(g).filter(a=>a.principalBasisMinor===5000000).length,2);assert.equal(charges(g).length,4)})
test('multiple required positions accrue independently and optional-only obligation never accrues',()=>{const f=fixture();let g=advanceReference(f.g,cycleOf(f.g).active.rounds[1].schedule.lateAt);const c=cycleOf(g),r=c.active.rounds[1];g=accruePenalties(g,r.schedule.lateAt,actual);const owner=c.active.obligations.find(o=>o.roundId===r.id&&o.memberId===f.organization.ownerMemberId),optional=c.active.obligations.find(o=>o.roundId===r.id&&o.memberId===f.memberId);assert.equal(charges(g,owner.id).length,2);assert.equal(charges(g,optional.id).length,0)})
test('same-date repeat and catch-up match daily runs',()=>{const f=fixture();let daily=f.g;for(let d=0;d<5;d++)daily=accruePenalties(daily,plus(f.late,d),actual);const caught=accruePenalties(f.g,plus(f.late,4),actual);assert.deepEqual(caught,daily);assert.deepEqual(accruePenalties(caught,plus(f.late,4),actual),caught)})
test('end of Cycle stops new accrual while preserving unpaid charges',()=>{const f=fixture();cycleOf(f.g).active.endedAt=plus(f.late,2);cycleOf(f.g).completedAt=plus(f.late,2);assert.equal(charges(accruePenalties(f.g,plus(f.late,7),actual),f.id).length,2)})
for(const rate of [-1,11,1.5,NaN,Infinity])test('invalid daily rate rejected: '+rate,()=>assert.throws(()=>validatePenaltyRate(rate)))
test('range 0-10 bps allowed, zero disables accrual, no accumulated-balance cap',()=>{for(const rate of [0,5,10])validatePenaltyRate(rate);const f=fixture();cycleOf(f.g).snapshot.terms.dailyPenaltyRateBps=0;assert.equal(sum(accruePenalties(f.g,plus(f.late,30),actual)),0);cycleOf(f.g).snapshot.terms.dailyPenaltyRateBps=10;cycleOf(f.g).snapshot.terms.defaultChargeCap=1;assert.ok(sum(accruePenalties(f.g,plus(f.late,10),actual))>100)})
test('accepted rate material, activation lock enforced and suitable seeded Groups use five bps',()=>{const o=org(),g=seedGroup(o,'draft-test','Ready for activation',exampleFeeBoundary()),c=cycleOf(g);assert.equal(c.terms.dailyPenaltyRateBps,5);const p=c.participants.find(p=>p.status==='approved');if(p){p.acceptances.push({actorId:p.id,at:actual,terms:memberTerms(c,p.id),revision:p.revision});assert.equal(accepted(c,p),true);c.terms.dailyPenaltyRateBps=6;assert.equal(accepted(c,p),false)}const f=fixture();assert.throws(()=>transition(f.g,f.organization,exampleFeeBoundary(),{type:'terms',terms:{...cycleOf(f.g).terms,dailyPenaltyRateBps:6}}),/protected/)})
test('audited waiver retains original accrual and cannot reduce principal or exceed unpaid amount',()=>{const f=fixture(),g=accruePenalties(f.g,f.late,actual),a=charges(g,f.id)[0],original=structuredClone(a),reason='Documented exceptional circumstances';const waived=waivePenalty(g,f.organization,f.organization.ownerMemberId,a.id,2000,reason,actual);assert.deepEqual(charges(waived,f.id)[0],original);assert.equal(penaltyBalance(waived,a).outstanding,3000);assert.equal(waived.penalties.waivers[0].at,actual);assert.equal(balances(cycleOf(waived).active.obligations.find(o=>o.id===f.id)).outstanding,10000000);assert.throws(()=>waivePenalty(waived,f.organization,f.organization.ownerMemberId,a.id,3001,reason,actual),/exceeds/);assert.throws(()=>waivePenalty(g,f.organization,f.memberId,a.id,1,reason,actual),/Owner/);assert.throws(()=>waivePenalty(g,f.organization,f.organization.ownerMemberId,a.id,1,'short',actual),/reason/)})
test('Owner cannot self-approve a beneficial waiver',()=>{const f=fixture(),g=accruePenalties(f.g,f.late,actual),a=charges(g).find(a=>a.memberId===f.organization.ownerMemberId);assert.throws(()=>waivePenalty(g,f.organization,f.organization.ownerMemberId,a.id,1,'Self benefit requires review',actual),/independent/)})
for(const days of [-1,0,6,6.999])test('no default before seven complete days after grace '+days,()=>{const f=fixture();received(f.g,f.memberId,plus(f.late,-2));assert.equal(evaluatePostPayoutDefaults(f.g,plus(f.late,days),actual).penalties?.defaults.length||0,0)})
test('no recognized payout means no default even after threshold',()=>{const f=fixture();assert.equal(evaluatePostPayoutDefaults(f.g,plus(f.late,8),actual).penalties?.defaults.length||0,0)})
test('threshold creates one historical default, linked Recovery and restrictions',()=>{const f=fixture(),g=evaluated(f),d=g.penalties.defaults[0],r=g.lifecycle.recoveries[0];assert.equal(g.penalties.defaults.length,1);assert.equal(d.thresholdAt,plus(f.late,7));assert.equal(d.recordedAt,actual);assert.equal(r.principalMinor,10000000);assert.equal(r.penaltyMinor,40000);assert.equal(r.restricted,true);assert.ok(r.restrictions.some(r=>r.reviewStatus==='active'));assert.deepEqual(evaluatePostPayoutDefaults(g,plus(f.late,7),actual),g)})
test('partial principal qualifies while zero-rate default remains independent',()=>{const f=fixture();pay(f.g,f.id,9000000,plus(f.late,1));cycleOf(f.g).snapshot.terms.dailyPenaltyRateBps=0;const g=evaluated(f);assert.equal(g.lifecycle.recoveries[0].principalMinor,1000000);assert.equal(g.lifecycle.recoveries[0].penaltyMinor,0)})
test('fully cleared required principal and penalty-only balances do not trigger default',()=>{const f=fixture();let g=accruePenalties(f.g,f.late,actual);pay(g,f.id,10000000,plus(f.late,1));received(g,f.memberId,f.late);g=evaluatePostPayoutDefaults(g,plus(f.late,7),actual);assert.equal(g.penalties.defaults.length,0);assert.equal(charges(g,f.id)[0].amountMinor,5000)})
test('optional-only recipient contribution cannot trigger default',()=>{const f=fixture();let g=advanceReference(f.g,cycleOf(f.g).active.rounds[1].schedule.lateAt);pay(g,f.id,10000000,plus(f.late,-1));received(g,f.memberId,f.late);const r=cycleOf(g).active.rounds[1];g=evaluatePostPayoutDefaults(g,plus(r.schedule.lateAt,7),actual);assert.equal(g.penalties?.defaults.length||0,0)})
test('unresolved payment exception does not turn unallocated money into principal satisfaction or new default',()=>{const f=fixture();(f.g.payments??=emptyPayments()).transactions.push({id:'exception',cycleId:cycleOf(f.g).id,memberId:f.memberId,allocationStatus:'exception'});const g=evaluated(f);assert.equal(g.penalties.defaults.length,0);assert.equal(charges(g,f.id)[0].principalBasisMinor,10000000)})
test('unconfirmed transfer does not establish receipt',()=>{const o=org(),g=payoutDemo(o,'unconfirmed','Transfer awaiting confirmation'),p=g.payouts.records[0],c=cycleOf(g);let next=advanceReference(g,c.active.rounds[1].schedule.lateAt);next=evaluatePostPayoutDefaults(next,plus(c.active.rounds[1].schedule.lateAt,7),actual);assert.ok(!next.penalties?.defaults.some(d=>d.memberId===p.memberId))})
test('Recovery is oldest principal first; penalty reductions target the correct day',()=>{const f=fixture();let g=evaluated(f),r=g.lifecycle.recoveries[0],a=charges(g,f.id).at(-1);g=waivePenalty(g,f.organization,f.organization.ownerMemberId,a.id,1000,'Approved daily penalty reduction',actual);r=g.lifecycle.recoveries[0];r.recoveredMinor=10002000;r.recoveryPayments=[{id:'recovery-receipt',amountMinor:r.recoveredMinor,businessAt:plus(f.late,7.5),recordedAt:actual}];const p=allocateRecovery(g,cycleOf(g));assert.equal(p.allocations.find(a=>a.kind==='principal').appliedMinor,10000000);assert.equal(p.allocations.filter(a=>a.kind==='penalty')[0].appliedMinor,2000);assert.equal(p.allocations.find(x=>x.sourceId===a.id).waivedMinor,1000);assert.equal(p.cases[0].issue,'');g=accruePenalties(g,plus(f.late,9),actual);assert.equal(charges(g,f.id).length,8)})
test('later Recovery and explicit resolution retain default and release restriction',()=>{const f=fixture();let g=evaluated(f),r=g.lifecycle.recoveries[0];r.recoveredMinor=r.principalMinor+r.penaltyMinor;r.recoveryPayments=[{id:'recovery-receipt',amountMinor:r.recoveredMinor,businessAt:plus(f.late,7.5),recordedAt:actual}];const event=structuredClone(g.penalties.defaults[0]);g=resolveRecovery(g,f.organization,r.id,plus(f.late,8));assert.deepEqual(g.penalties.defaults[0],event);assert.equal(g.lifecycle.recoveries[0].restricted,false);assert.equal(g.lifecycle.recoveries[0].status,'resolved');assert.equal(g.lifecycle.recoveries[0].restrictions[0].reviewStatus,'released')})
test('excess Recovery remains an exception and cannot be resolved as cleared',()=>{const f=fixture(),g=evaluated(f),r=g.lifecycle.recoveries[0];r.recoveredMinor=r.principalMinor+r.penaltyMinor+1;assert.equal(recoveryBalances(r).excessMinor,1);assert.equal(allocateRecovery(g,cycleOf(g)).cases[0].issue,'Recovery Payment Exception');assert.throws(()=>resolveRecovery(g,f.organization,r.id,plus(f.late,8)),/Outstanding/)})
test('untraceable legacy principal and aggregate Recovery history fail safely without rewriting facts',()=>{const f=fixture();cycleOf(f.g).active.obligations.find(o=>o.id===f.id).components[0].requiredSatisfiedMinor=1;assert.throws(()=>accruePenalties(f.g,f.late,actual),/Dated principal/);const clean=fixture(),g=evaluated(clean);g.lifecycle.recoveries[0].recoveredMinor=1;assert.throws(()=>accruePenalties(g,plus(clean.late,8),actual),/Dated Recovery/)})
test('Member, Organization and internal reports reconcile ledger without double counting linked Recovery',()=>{const f=fixture();let g=evaluated(f),a=charges(g,f.id)[0];g=waivePenalty(g,f.organization,f.organization.ownerMemberId,a.id,1000,'Report waiver audit reason',actual);const sources={organizations:[{...f.organization,name:f.organization.form.name,workspace:true}],worlds:[{groups:[g]}],clients:[],triage:{}};const owner={kind:'organization',organizationId:f.organization.id,memberId:f.organization.ownerMemberId};const report=generateReport(sources,owner,'organization-collections');const rows=report.rows.filter(r=>r.source.kind==='daily-penalty');assert.equal(rows.length,g.penalties.accruals.length);assert.equal(report.rows.filter(r=>r.source.kind==='recovery-penalty').length,0);assert.equal(rows.reduce((n,r)=>n+r.values.penaltyWaived,0),1000);const member=generateReport(sources,{kind:'member',memberId:f.memberId},'member-obligations');assert.ok(member.rows.every(r=>r.memberId===f.memberId));assert.ok(member.rows.some(r=>r.source.kind==='daily-penalty'));const internal=generateInternalReport(sources,seedSession('finance-reviewer'),'internal-financial');assert.ok(internal.rows.some(r=>r.values.penaltyAccrued===5000))})
test('scheduler catch-up, default step, retry and same-date idempotency share domain services',()=>{const f=fixture();received(f.g,f.memberId,f.late);cycleOf(f.g).active.timeSource='ENVIRONMENT';const settings=createSettings();settings.mode='CONTROLLED';settings.controlledDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos'}).format(new Date(plus(f.late,7)));const state=createProcessState(),sources={worlds:[{groups:[f.g]}],organizations:[f.organization],banks:{}},actor=seedSession('ops-supervisor');const run=(beforeRecord,retryOf)=>{const p=previewProcess(actor,sources,'Financial rule validation',retryOf,state,settings,actual);return executeProcess(actor,sources,p,true,{state,settings,now:()=>actual,beforeRecord})};const first=run(key=>{if(key==='POST_PAYOUT_DEFAULT')throw Error('Test interruption')});assert.equal(first.status,'PARTIAL_FAILURE');assert.ok(sources.worlds[0].groups[0].penalties.accruals.length>0);const second=run(undefined,first.id);assert.ok(second.steps.some(s=>s.key==='PENALTY_ACCRUAL'&&s.changed===0));assert.equal(sources.worlds[0].groups[0].penalties.defaults.length,1);const before=structuredClone(sources);assert.equal(run().status,'COMPLETED_WITH_NO_CHANGES');assert.deepEqual(sources,before)})
test('partial Recovery reduces only future principal basis and retains earlier charges',()=>{const f=fixture();let g=evaluated(f),r=g.lifecycle.recoveries[0];r.recoveredMinor=4000000;r.recoveryPayments=[{id:'partial-recovery',amountMinor:4000000,businessAt:plus(f.late,7.5),recordedAt:actual}];g=accruePenalties(g,plus(f.late,9),actual);assert.deepEqual(charges(g,f.id).slice(-2).map(a=>a.principalBasisMinor),[6000000,6000000]);assert.equal(charges(g,f.id)[0].principalBasisMinor,10000000)})
test('dated Recovery never reallocates previously paid penalties to later-generated principal',()=>{const f=fixture();let g=evaluated(f),r=g.lifecycle.recoveries[0];r.recoveredMinor=r.principalMinor+2000;r.recoveryPayments=[{id:'dated-recovery',amountMinor:r.recoveredMinor,businessAt:plus(f.late,7.5),recordedAt:actual}];const paid=allocateRecovery(g,cycleOf(g)).allocations.find(a=>a.kind==='penalty'&&a.appliedMinor);g=advanceReference(g,cycleOf(g).active.rounds[2].schedule.opensAt);g=evaluatePostPayoutDefaults(g,cycleOf(g).active.referenceAt,actual);const after=allocateRecovery(g,cycleOf(g));assert.equal(after.allocations.find(a=>a.sourceId===paid.sourceId).appliedMinor,2000);assert.ok(after.allocations.some(a=>a.kind==='principal'&&a.outstandingMinor>0&&a.appliedMinor===0))})
test('new unpaid obligations after a resolved case can default without overlapping historical scope',()=>{const f=fixture();let g=evaluated(f),r=g.lifecycle.recoveries[0];r.recoveredMinor=r.principalMinor+r.penaltyMinor;r.recoveryPayments=[{id:'cleared-recovery',amountMinor:r.recoveredMinor,businessAt:plus(f.late,7.5),recordedAt:actual}];g=resolveRecovery(g,f.organization,r.id,plus(f.late,8));const third=cycleOf(g).active.rounds[2],at=plus(third.schedule.lateAt,7);g=advanceReference(g,at);g=accruePenalties(g,at,actual);g=evaluatePostPayoutDefaults(g,at,actual);assert.equal(g.penalties.defaults.length,2);assert.equal(g.lifecycle.recoveries[0].status,'resolved');assert.equal(g.lifecycle.recoveries[1].status,'open');assert.ok(allocateRecovery(g,cycleOf(g)).cases.every(c=>!c.issue))})
for(const frequency of ['Daily','Weekly','Biweekly'])test('calendar boundary and seven-day default for '+frequency,()=>{const f=fixture(frequency);const g=accruePenalties(f.g,f.late,actual);assert.equal(charges(g,f.id).length,1);received(g,f.memberId,plus(f.late,-1));assert.equal(evaluatePostPayoutDefaults(g,new Date(Date.parse(plus(f.late,7))-1).toISOString(),actual).penalties?.defaults.length||0,0)})
test('recognized payout must exist by evaluation time',()=>{const f=fixture();received(f.g,f.memberId,plus(f.late,8));assert.equal(evaluatePostPayoutDefaults(f.g,plus(f.late,7),actual).penalties?.defaults.length||0,0);assert.equal(evaluatePostPayoutDefaults(f.g,plus(f.late,8),actual).penalties.defaults.length,1)})
test('ungenerated source and altered rate above accepted ceiling are rejected or excluded',()=>{const f=fixture();cycleOf(f.g).active.generatedRoundIds=[];assert.equal(sum(accruePenalties(f.g,plus(f.late,7),actual)),0);cycleOf(f.g).snapshot.terms.dailyPenaltyRateBps=11;assert.throws(()=>accruePenalties(f.g,plus(f.late,7),actual),/ceiling/)})
test('Business Date rollback guard sees posted daily business history and actual audit stays actual',async()=>{const {protectedHistory}=await import('../src/settings/history.ts');const f=fixture(),g=accruePenalties(f.g,plus(f.late,6),actual);const latest=charges(g).at(-1);assert.equal(protectedHistory([{groups:[g]}]),latest.accrualDate);assert.equal(latest.recordedAt,actual)})
