import { seedSession } from '../src/access/seeds.ts'
﻿import test from 'node:test'
import assert from 'node:assert/strict'
import {seedPersona,demoPersonas} from '../src/clients/seeds.ts'
import {seedOrganization} from '../src/organizations/seeds.ts'
import {operationsDemoWorld} from '../src/operations/seeds.ts'
import {decisionDemoWorld} from '../src/operations/decisionSeeds.ts'
import {projectCases} from '../src/operations/sources.ts'
import {previewDecision,executeDecision} from '../src/operations/decisions.ts'
import {allocationChoices} from '../src/operations/allocation.ts'
import {permittedActions} from '../src/operations/review.ts'
import {reconcile} from '../src/reconciliation/service.ts'
import {respondToVerification} from '../src/clients/service.ts'
import {respondToInformation} from '../src/organizations/service.ts'
const actor=id=>(seedSession(id)),verification=actor('verification-reviewer'),finance=actor('finance-reviewer'),supervisor=actor('ops-supervisor'),analyst=actor('ops-analyst'),at='2100-01-01T00:00:00Z'
function setup(extra=false){const m=seedPersona('verified'),org=seedOrganization(m,'active'),w=operationsDemoWorld(org);if(extra){const d=decisionDemoWorld(org);w.groups.push(...d.groups);for(const key of ['settlements','unmatchedPayments','cases','receivables','history','expectations'])w.finance[key].push(...d.finance[key])}return {clients:demoPersonas.map(p=>seedPersona(p.id)),organizations:[org,seedOrganization(m,'pending'),seedOrganization(m,'settlement-pending')],worlds:[w]}}
const find=(s,type)=>projectCases(s,supervisor).find(c=>c.type===type&&!['Resolved','Closed'].includes(c.status))
const input=action=>({action,reason:'Source evidence and original record inspected',comments:'INTERNAL PRIVATE COMMENT',evidence:['BANK-EVIDENCE-5B'],evidenceConfirmed:true})
function decide(s,c,action,a,patch={}){const p=previewDecision(s,c.id,{...input(action),...patch},a,at);return executeDecision(s,p,a,at).sources}
for(const [action,status] of [['approve','verified'],['request-information','information-required'],['reject','rejected']])test('KYC '+action+' updates same identity and audited source',()=>{const s=setup(),c=find(s,'Member KYC Review'),m=s.clients.find(m=>m.id===c.memberId),next=decide(s,c,action,verification),n=next.clients.find(m=>m.id===m?.id&&m.id===c.memberId);assert.equal(n.verification.status,status);assert.equal(n.id,m.id);assert.deepEqual(n.verification.submission,m.verification.submission);assert.equal(n.verification.review.decisions.length,1);assert.equal(s.clients.find(m=>m.id===c.memberId).verification.status,'pending');assert.ok(!n.history.at(-1).action.includes('PRIVATE'));if(action==='request-information'){const response=respondToVerification(n,'Requested information supplied',null);assert.equal(response.verification.status,'pending');assert.equal(response.verification.review.decisions.length,1)}})
for(const [action,status] of [['approve','approved'],['request-information','information-required'],['reject','declined']])test('Organization '+action+' preserves application and Owner',()=>{const s=setup(),c=find(s,'Organization Application Review'),org=s.organizations.find(o=>o.id===c.organizationId),next=decide(s,c,action,verification),n=next.organizations.find(o=>o.id===org.id);assert.equal(n.status,status);assert.equal(n.ownerMemberId,org.ownerMemberId);assert.deepEqual(n.application.snapshot,org.application.snapshot);if(action==='request-information'){const response=respondToInformation(n,next.clients.find(m=>m.id===n.ownerMemberId),'Documents supplied',null);assert.equal(response.application.review.caseStatus,'In Review')}})
test('Settlement-account approval waits for provider; rejection preserves effective account',()=>{for(const action of ['approve','reject','request-information']){const s=setup(),c=find(s,'Settlement Account Change Review'),org=s.organizations.find(o=>o.id===c.organizationId),next=decide(s,c,action,finance),n=next.organizations.find(o=>o.id===org.id);assert.deepEqual(n.settlement,org.settlement);assert.equal(n.settlementChanges[0].status,action==='approve'?'approved':action==='reject'?'rejected':'information-required');if(action==='approve')assert.equal(projectCases(next,finance).find(x=>x.id===c.id).status,'Awaiting External Action')}})
test('Manual acceptance allocates once, remains manual; rejected claim satisfies nothing',()=>{const s=setup(),c=find(s,'Manual Contribution Review'),choices=allocationChoices(s,c);assert.ok(choices.length);const before=structuredClone(s),next=decide(s,c,'accept-manual',finance,{targetId:choices[0].id}),g=next.worlds[0].groups.find(g=>g.id===c.groupId),m=g.manualContributions[0];assert.equal(m.status,'allocated');assert.equal(m.allocatedMinor,m.amountMinor);assert.equal(m.source,'organization-confirmed-manual');assert.ok(g.payments.allocations.some(a=>a.transactionId===m.id&&a.source==='organization-confirmed-manual'));assert.deepEqual(s,before);assert.equal(projectCases(next,finance).find(x=>x.id===c.id).status,'Resolved');assert.throws(()=>decide(next,c,'accept-manual',finance));const rejected=decide(s,c,'reject',finance);assert.equal(rejected.worlds[0].groups.find(g=>g.id===c.groupId).manualContributions[0].allocatedMinor,0)})
test('Owner manual recording cannot recognize itself; independent TCS review required',()=>{const s=setup(true),c=projectCases(s,finance).find(c=>c.type==='Manual Contribution Review'&&c.groupId.endsWith('5b-manual')),g=s.worlds[0].groups.find(g=>g.id===c.groupId);assert.equal(g.manualContributions[0].allocatedMinor,0);assert.throws(()=>decide(s,c,'accept-manual',{kind:'organization',personaId:g.organizationId}));assert.throws(()=>decide(s,c,'accept-manual',analyst));const next=decide(s,c,'accept-manual',finance,{targetId:allocationChoices(s,c)[0].id});assert.equal(next.worlds[0].groups.find(g=>g.id===c.groupId).manualContributions[0].review.decisions[0].reviewerId,'finance-reviewer')})
test('Unallocated exact Member payment links safely and preserves original provider evidence',()=>{const s=setup(true),c=projectCases(s,finance).find(c=>c.source.id.includes('UNMATCHED-5B-C2')),choices=allocationChoices(s,c);assert.ok(choices.length);const original=structuredClone(s.worlds[0].finance.unmatchedPayments),next=decide(s,c,'allocate',finance,{targetId:choices[0].id});assert.deepEqual(next.worlds[0].finance.unmatchedPayments,original);const row=projectCases(next,finance).find(x=>x.id===c.id);assert.equal(row.status,'Resolved');assert.equal(row.groupId,choices[0].groupId);assert.throws(()=>decide(s,c,'allocate',finance,{targetId:'other-tenant-obligation'}))})
test('Amount mismatch cannot pay a full obligation when partial contributions are prohibited',()=>{const s=setup(),c=find(s,'Amount Mismatch');assert.equal(allocationChoices(s,c).length,0);assert.throws(()=>decide(s,c,'allocate',finance,{targetId:'anything'}));const next=decide(s,c,'resolution-required',finance);assert.notEqual(projectCases(next,finance).find(x=>x.id===c.id).status,'Resolved')})
test('Settlement relinking preserves original gross/net/lines and records correction; variance cannot be forced balanced',()=>{let s=setup(true),c=projectCases(s,finance).find(c=>c.type==='Settlement Exception'&&c.source.id.includes('ops-5b-0'));assert.ok(c);const b=s.worlds[0].finance.settlements.find(b=>b.id===c.source.id),original=structuredClone(b),g=s.worlds[0].groups.find(g=>g.id.endsWith('ops-5b-0'));for(const line of b.lines){const tx=g.payments.transactions.find(t=>'UNKNOWN-'+t.providerReference===line.providerReference);s=decide(s,projectCases(s,finance).find(x=>x.id===c.id),'correct-link',finance,{targetId:tx.id,settlementLineReference:line.providerReference})}const n=s.worlds[0].finance.settlements.find(b=>b.id===b?.id&&b.id===c.source.id);assert.equal(n.status,'matched');assert.equal(n.netMinor,original.netMinor);assert.deepEqual(n.lines,original.lines);assert.ok(n.reconciliationLinks.length);const variance=find(s,'Settlement Variance');assert.throws(()=>decide(s,variance,'confirm-match',finance));const next=decide(s,variance,'escalate-provider',finance);assert.equal(projectCases(next,finance).find(x=>x.id===variance.id).status,'Awaiting External Action')})
test('Revenue confirmation settles exact receipt and updates source clearance; mismatch stays due',()=>{const s=setup(true),c=find(s,'TCS Revenue Share — Awaiting Confirmation'),next=decide(s,c,'confirm-receipt',finance),r=next.worlds[0].finance.receivables.find(r=>r.id===c.source.id);assert.equal(r.status,'settled');assert.equal(r.payments[0].confirmedBy,'finance-reviewer');assert.equal(projectCases(next,finance).find(x=>x.id===c.id).status,'Resolved');const mismatch=find(next,'TCS Revenue Share Payment Exception');assert.throws(()=>decide(next,mismatch,'confirm-receipt',finance));assert.throws(()=>decide(s,c,'confirm-receipt',analyst))})
test('Amendment approval preserves terms and awaits required Member consent',()=>{const s=setup(),c=find(s,'Cycle Amendment Request'),g=s.worlds[0].groups.find(g=>g.id===c.groupId),next=decide(s,c,'approve',supervisor),n=next.worlds[0].groups.find(g=>g.id===c.groupId);assert.deepEqual(n.cycles,g.cycles);assert.equal(n.lifecycle.amendments[0].status,'approved-awaiting-consent');assert.equal(projectCases(next,supervisor).find(x=>x.id===c.id).status,'Awaiting External Action')})
test('Force Close retains liabilities and requires Supervisor; termination blocked',()=>{const s=setup(),c=find(s,'Force Close Request'),g=s.worlds[0].groups.find(g=>g.id===c.groupId),next=decide(s,c,'approve',supervisor),n=next.worlds[0].groups.find(g=>g.id===c.groupId);assert.equal(n.cycles[0].status,'force-closed');assert.deepEqual(n.cycles[0].active.obligations,g.cycles[0].active.obligations);assert.deepEqual(n.lifecycle.payoutFacts,g.lifecycle.payoutFacts);assert.throws(()=>decide(s,c,'approve',finance));assert.throws(()=>decide(s,c,'approve',analyst));s.worlds[0].groups.find(g=>g.id===c.groupId).lifecycle.termination={status:'pending-tcs-review',at,reason:'Cannot complete Group with unpaid liabilities'};assert.throws(()=>decide(s,find(s,'Group Termination Review'),'approve',supervisor))})
test('Independent recommendation blocks same approver; stale previews, missing reasons and evidence rejected',()=>{const s=setup(),c=find(s,'Force Close Request'),recommended=decide(s,c,'recommend',finance);assert.equal(projectCases(recommended,supervisor).find(x=>x.id===c.id).status,'Awaiting Approval');const next=decide(recommended,c,'approve',supervisor);assert.equal(next.worlds[0].groups.find(g=>g.id===c.groupId).lifecycle.forceCloseRequests[0].review.decisions.length,2);const self=setup(),req=self.worlds[0].groups.find(g=>g.id===c.groupId).lifecycle.forceCloseRequests[0];req.review={caseStatus:'Awaiting Approval',state:'Recommended',decisions:[],approvalPolicy:'independent',recommendedBy:'ops-supervisor'};assert.throws(()=>decide(self,c,'approve',supervisor));const k=find(s,'Member KYC Review'),p=previewDecision(s,k.id,input('approve'),verification,at);s.clients[0].history.push({at,action:'Changed source'});assert.throws(()=>executeDecision(s,p,verification,at),/changed/);assert.throws(()=>decide(setup(),c,'approve',supervisor,{reason:'',evidence:[]}))})
test('5C authority extension retains one projection per source',()=>{const s=setup(),cases=projectCases(s,supervisor);for(const c of cases.filter(c=>['Payout Dispute','Post-Payout Recovery','Organization Payout Breach'].includes(c.type)))assert.ok(permittedActions(c,supervisor).includes('request-information'));assert.deepEqual(projectCases(s,supervisor).map(c=>c.id),cases.map(c=>c.id));assert.equal(new Set(cases.map(c=>c.id)).size,cases.length)})

test('Approved financial amendment with all consent waits for application rule and preserves generated history',async()=>{
 const {lifecycleTransition}=await import('../src/lifecycle/service.ts')
 let s=setup(),c=find(s,'Cycle Amendment Request');s=decide(s,c,'approve',supervisor)
 const index=s.worlds[0].groups.findIndex(g=>g.id===c.groupId),original=structuredClone(s.worlds[0].groups[index].cycles)
 for(const id of s.worlds[0].groups[index].lifecycle.amendments[0].affectedMemberIds){const g=s.worlds[0].groups[index];s.worlds[0].groups[index]=lifecycleTransition(g,id,s.organizations[0].ownerMemberId,{type:'consent-amendment',id:g.lifecycle.amendments[0].id,memberId:id},at)}
 const n=s.worlds[0].groups[index];assert.deepEqual(n.cycles,original);assert.equal(n.lifecycle.amendments[0].review.state,'Approved — awaiting financial application rule');assert.equal(projectCases(s,supervisor).find(x=>x.id===c.id).status,'Awaiting External Action');assert.throws(()=>decide(s,c,'reject',supervisor))
})
test('Consented non-financial amendment changes presentation only',()=>{
 let s=setup(),c=find(s,'Cycle Amendment Request'),g=s.worlds[0].groups.find(g=>g.id===c.groupId),a=g.lifecycle.amendments[0]
 a.proposedTerms={...a.currentTerms,description:'Revised community description'};a.consents=a.affectedMemberIds.map(memberId=>({memberId,at,terms:JSON.stringify(a.proposedTerms)}));const snapshot=structuredClone(g.cycles[0].snapshot),obligations=structuredClone(g.cycles[0].active.obligations)
 s=decide(s,c,'approve',supervisor);g=s.worlds[0].groups.find(g=>g.id===c.groupId);assert.equal(g.description,'Revised community description');assert.deepEqual(g.cycles[0].snapshot,snapshot);assert.deepEqual(g.cycles[0].active.obligations,obligations);assert.equal(g.lifecycle.amendments[0].status,'effective')
})
test('Aggregate principal absorption never executes or erases debt',()=>{
 const s=setup(),c=find(s,'Force Close Request');s.worlds[0].groups.find(g=>g.id===c.groupId).lifecycle.forceCloseRequests[0].requestedAbsorptionMinor=10000;const before=structuredClone(s)
 assert.throws(()=>decide(s,c,'approve',supervisor),/exact liability records/);assert.deepEqual(s,before)
})
test('Provider confirmation activates approved account separately and preserves old settlement snapshots',async()=>{
 const {applyPrototypeSettlementUpdate}=await import('../src/organizations/service.ts')
 const s=setup(),c=find(s,'Settlement Account Change Review'),next=decide(s,c,'approve',finance),org=next.organizations.find(o=>o.id===c.organizationId),change=org.settlementChanges[0]
 assert.throws(()=>applyPrototypeSettlementUpdate(s.organizations.find(o=>o.id===c.organizationId),{kind:'prototype-provider-update-confirmed',requestId:change.id,reference:'DEMO-PROVIDER-TEST',at}))
 const updated=applyPrototypeSettlementUpdate(org,{kind:'prototype-provider-update-confirmed',requestId:change.id,reference:'DEMO-PROVIDER-TEST',at});assert.deepEqual(updated.settlement,change.proposed);assert.deepEqual(updated.settlementChanges[0].previous,change.previous);assert.equal(updated.settlementChanges[0].review.caseStatus,'Resolved');assert.equal(updated.settlementChanges[0].review.decisions.length,1)
})

test('Permitted partial allocation preserves immutable before/after audit snapshots',()=>{
 const s=setup(),c=find(s,'Amount Mismatch'),g=s.worlds[0].groups.find(g=>g.id===c.groupId)
 g.cycles[0].active.contributionPolicy={partial:'allowed',advance:'unconfigured'}
 const choice=allocationChoices(s,c)[0];assert.ok(choice)
 const next=decide(s,c,'allocate',finance,{targetId:choice.id}),row=projectCases(next,finance).find(x=>x.id===c.id),d=row.review.decisions[0]
 assert.ok(d.before.payment.unallocatedMinor>0);assert.equal(d.after.payment.unallocatedMinor,0);assert.equal(d.before.payment.allocatedMinor,0);assert.ok(d.after.payment.allocatedMinor>0)
 const source=next.worlds[0].groups.find(g=>g.id===c.groupId).payments.transactions.find(t=>t.id===c.source.id)
 assert.equal(source.amountMinor,d.before.payment.amountMinor);assert.equal(source.providerReference,d.before.payment.providerReference)
 const historical=structuredClone(d.after);source.allocationStatus='exception';assert.deepEqual(d.after,historical)
})
