import type { Audience, ReportColumn, ReportDefinition } from './model.ts'
const text = (key: string, label: string): ReportColumn => ({ key, label, type: 'text' })
const money = (key: string, label: string, total = true): ReportColumn => ({ key, label, type: 'money', total })
const number = (key: string, label: string): ReportColumn => ({ key, label, type: 'number', total: true })
const context = [text('organization', 'Organization'), text('group', 'Group'), text('cycle', 'Cycle')]
const member = [...context, text('member', 'Member'), text('position', 'Position / share')]
const round = text('round', 'Round'), status = text('status', 'Status')
const date: ReportColumn = { key: 'date', label: 'Source date', type: 'date' }
const contribution = [...member, round, money('received', 'Recorded payment'), money('allocated', 'Allocated'), money('unallocated', 'Unallocated'), text('source', 'Payment origin'), text('settlement', 'Settlement indicator'), text('reference', 'Reference'), status, date]
const obligation = [...member, round, money('expected', 'Original Principal'), money('satisfied', 'Satisfied principal'), money('recoveryApplied', 'Recovery Applied'), money('outstanding', 'Net Principal Outstanding'), money('penaltyAccrued', 'Penalty accrued'), money('penaltyWaived', 'Penalty waived'), money('penaltyOutstanding', 'Penalty Outstanding'), money('penaltyRecoveryApplied', 'Penalty Recovery Applied'), money('optionalPaid', 'Optional contributed'), text('optional', 'Optional choice'), text('stage', 'Aging / Default State'), status, { ...date, label: 'Original Due Date' }]
const payout = [...member, round, money('entitlement', 'Scheduled entitlement'), money('fee', 'Agreed fee'), money('net', 'Expected net'), money('transferred', 'Recorded transfer'), money('evidenced', 'Evidenced receipt'), money('outstanding', 'Source payout outstanding'), status, date]
function definition(id: string, name: string, category: string, audience: Audience, description: string, dateBasis: string, columns: ReportColumn[], filters: string[]): ReportDefinition {
  return { id, name, category, audience, description, dateBasis, columns, filters,
    visibility: audience === 'member' ? 'Authenticated Member: own records only' : 'Authenticated Organization Owner: owned workspace only' }
}
const dimensions = ['organizationId', 'groupId', 'cycleId', 'frequency', 'status']
const people = [...dimensions, 'memberId', 'position']
const rounds = [...people, 'roundId']
export const reportCatalogue: ReportDefinition[] = [
  definition('member-contributions', 'My Contributions', 'Contributions', 'member', 'Recorded payments, allocation and exceptions across your Organizations.', 'Payment / confirmation date', contribution.filter(c => c.key !== 'member'), rounds.filter(k => k !== 'memberId')),
  definition('member-obligations', 'My Obligations', 'Obligations', 'member', 'Generated obligations only. Skipped optional contributions are not debt.', 'Round due date', obligation.filter(c => c.key !== 'member'), rounds.filter(k => k !== 'memberId')),
  definition('member-payouts', 'My Payouts', 'Payouts', 'member', 'Scheduled entitlement, recorded transfer and receipt evidence.', 'Payout target date', payout.filter(c => c.key !== 'member'), rounds.filter(k => k !== 'memberId')),
  definition('member-participation', 'My Participation', 'Participation', 'member', 'Current and historical participation, including exits and completed Cycles.', 'Cycle start date', [...context, text('position', 'Position / payout order'), status, text('lifecycle', 'Cycle lifecycle'), date], dimensions),
  definition('organization-cycles', 'Groups & Cycles', 'Groups / Cycles', 'organization', 'Every Cycle, including cancelled, completed and force-closed history.', 'Cycle start date', [...context, text('frequency', 'Frequency'), number('members', 'Members'), number('positions', 'Equivalent positions'), money('spv', 'Scheduled payout value', false), money('expected', 'Generated principal'), money('collected', 'Recognized collection'), money('outstanding', 'Net Principal Outstanding'), money('payoutOutstanding', 'Source payout outstanding'), money('payoutTransferred', 'Recorded payout transfers'), number('recoveries', 'Recovery cases'), status], dimensions),
  definition('organization-collections', 'Collections', 'Collections', 'organization', 'One row per generated Member/Round obligation, with linked payment records in detail.', 'Round due date; payment dates in detail', [...obligation, money('collected', 'Recognized collection'), text('references', 'Payment references')], rounds),
  definition('organization-payments', 'Payment Register', 'Collections', 'organization', 'Provider and manual payments, advance reservations and exceptions, independent of obligation generation.', 'Payment / confirmation date', contribution, rounds),
  definition('organization-rounds', 'Round Collection Summary', 'Collections', 'organization', 'Required and optional collections, fulfillment and payout readiness.', 'Round due date', [...context, round, money('expected', 'Required collection'), money('collected', 'Recognized collection'), money('outstanding', 'Net Principal Outstanding'), number('members', 'Members expected'), number('positions', 'Positions expected'), number('fully', 'Fully paid'), number('partial', 'Partially paid'), number('unpaid', 'Unpaid'), number('skipped', 'Optional skipped'), number('optionalMembers', 'Optional contributors'), money('optionalPaid', 'Optional contributed'), status, date], [...dimensions, 'roundId']),
  definition('organization-obligations', 'Outstanding & Aging', 'Obligations', 'organization', 'Net obligations at the original due dates, including historical rows cleared by Recovery.', 'Round due date', [...obligation, text('days', 'Days past due')], rounds),
  definition('organization-payouts', 'Payouts', 'Payouts', 'organization', 'Payout obligations, transfer history, evidence, disputes and breaches.', 'Payout target date', payout, rounds),
  definition('organization-recovery', 'Defaults & Recovery', 'Defaults / Recovery', 'organization', 'Original liability and aggregate recoveries allocated principal first, then penalty.', 'Recovery opened date', [...member, money('principal', 'Original principal'), money('penalty', 'Accrued penalty'), money('recovered', 'Recovered total'), money('principalOutstanding', 'Principal outstanding'), money('penaltyOutstanding', 'Penalty outstanding'), money('waived', 'Penalty waived'), money('outstanding', 'Total outstanding'), text('restriction', 'Restriction'), status, date], people),
  definition('organization-exits', 'Exit Settlements', 'Exit Settlements', 'organization', 'Organization responsibility to outgoing Members; separate from Member default.', 'Settlement due date, or request date if not scheduled', [...member, money('contributions', 'Recognized contributions'), money('due', 'Settlement due'), money('settled', 'Settled'), money('outstanding', 'Outstanding'), text('replacement', 'Replacement / regularization'), status, date], people),
  definition('organization-fees', 'Organization Fees', 'Fees', 'organization', 'Installment recognition with final evidence and preserved original postings.', 'Installment recorded date', [...member, round, text('reference', 'Installment'), money('recordedFee', 'Original fee recognition'), money('recognized', 'Outcome fee recognition'), money('adjustment', 'Fee adjustment required'), status, date], rounds),
  definition('organization-revenue', 'TCS Revenue Share', 'Fees', 'organization', 'Your Organization’s posted obligations and receipt confirmations; later adjustments remain separate.', 'Revenue share due date', [...context, money('recognized', 'Posted Organization fee'), money('due', 'Posted TCS share due'), money('transferred', 'Recorded transfer'), money('confirmed', 'Confirmed receipt'), money('outstanding', 'Posted outstanding'), money('adjustment', 'Share adjustment required'), text('reference', 'Payment reference'), status, date], dimensions),
]
export function catalogueFor(audience: Audience) { return reportCatalogue.filter(d => d.audience === audience) }
