import type { ReportColumn, ReportDefinition } from './model.ts'
export const column = (key: string, label: string, type: ReportColumn['type'] = 'text', total = false): ReportColumn => ({ key, label, type, total })
const t = column
const m = (key: string, label: string) => t(key, label, 'money', true)
const context = [t('organization', 'Organization'), t('group', 'Group'), t('cycle', 'Cycle'), t('member', 'Member')]
const status = t('status', 'Status'), date = t('date', 'Source date', 'date')
const dims = ['organizationId', 'groupId', 'cycleId', 'status']
function def(id: string, name: string, category: string, permission: string, description: string, columns: ReportColumn[], filters: string[], source: string, dateBasis = 'Source event timestamp'): ReportDefinition {
 return { id: 'internal-' + id, name, category, audience: 'internal', permission: 'reports.' + permission + '.view', domain: category, sourceDescription: source, availability: 'Available', visibility: 'Active internal user with exact report permission', description, dateBasis, columns, filters }
}
export const internalCatalogue: ReportDefinition[] = [
 def('overview', 'Platform Overview', 'Platform', 'platform', 'Source records behind platform counts. Select a metric to inspect its rows.', [t('entity', 'Entity'), t('type', 'Record type'), status, t('members', 'Members', 'number', true), t('verified', 'Verified Members', 'number', true), t('restricted', 'Restricted / suspended Members', 'number', true), t('organizations', 'Organizations', 'number', true), t('activeOrganizations', 'Approved / active Organizations', 'number', true), t('groups', 'Groups', 'number', true), t('activeCycles', 'Active Cycles', 'number', true), t('completedCycles', 'Completed Cycles', 'number', true), t('forceClosed', 'Force-closed Cycles', 'number', true), t('activeCases', 'Active Operations cases', 'number', true), t('paymentExceptions', 'Unresolved payment exceptions', 'number', true), t('disputes', 'Open disputes', 'number', true), t('defaults', 'Post-Payout Defaults', 'number', true), t('breaches', 'Payout breaches', 'number', true), date], ['organizationId', 'type', 'status'], 'Clients, Organizations, Groups/Cycles and projected Operations cases'),
 def('growth', 'Member / Organization Growth', 'Platform', 'platform', 'Recorded registration, verification, application, approval and activation events. Missing dates are disclosed.', [t('entity','Member / Organization'),t('type','Event'),status,date,t('events','Events','number',true)], ['organizationId','type','status'], 'Entity history and lifecycle timestamps'),
 def('cycles', 'Group / Cycle Activity', 'Platform', 'platform', 'All Cycle lifecycles, frequencies and participation, including retained historical Cycles.', [...context,t('frequency','Frequency'),t('members','Member participations','number',true),t('positions','Equivalent positions','number',true),status,date], [...dims,'frequency'], 'Shared Group/Cycle records', 'Group creation / Cycle start date'),
 def('financial', 'Financial Activity', 'Financial', 'financial', 'Thrift activity and liabilities; these are not all Corestack-owned funds. Measures have separate source grains and are not additive.', [...context,t('type','Source measure'),m('expected','Required contributions'),m('collected','Recognized contributions'),m('principal','Net principal outstanding'),m('penaltyAccrued','Penalty accrued'),m('penaltyWaived','Penalty waived'),m('penaltyRecoveryApplied','Penalty recovered'),m('penalty','Penalty outstanding'),m('entitlement','Payout entitlement'),m('evidenced','Evidenced receipt'),m('payoutOutstanding','Payout outstanding'),m('feePosted','Original Organization fee recognition'),m('feeRecognized','Outcome Organization fee'),m('feeAdjustment','Fee adjustment required (signed)'),m('shareDue','Posted TCS share'),m('shareConfirmed','Confirmed TCS receipt'),m('shareOutstanding','Posted share outstanding'),m('shareAdjustment','Share adjustment required (signed)'),status,date], [...dims,'type'], '7A obligation, payout, fee and revenue projections'),
 def('revenue','TCS Revenue Share','Financial','financial','Original postings, recorded transfers, confirmed receipts and separate adjustment requirements.',[...context,m('recognized','Posted Organization fee'),t('shareRate','TCS share rate (%)'),m('due','Posted TCS share due'),m('transferred','Organization recorded transfer'),m('confirmed','Confirmed TCS receipt'),m('outstanding','Posted outstanding'),m('adjustment','Adjustment required (signed)'),t('reference','Payment reference'),t('aging','Aging state'),t('restriction','Restriction'),status,date],dims,'Revenue receivables, payments and adjustment-review records','Original share due date'),
 def('payments','Payment Exceptions','Financial','financial','Distinct payment exceptions and their current Operations handling; not a combined payment status.',[...context,t('reference','Case reference'),t('type','Exception type'),m('amount','Case amount'),t('source','Payment source'),t('allocation','Allocation state'),t('assignee','Assignee'),t('ageHours','Elapsed hours','number'),status,date], [...dims,'type','assignee','age'], 'Module 5 case projection and payment source records'),
 def('reconciliation','Reconciliation','Financial','financial','Original provider settlement values and reconciliation links; missing expectations remain unavailable.',[t('organization','Organization'),t('reference','Settlement reference'),t('provider','Provider'),t('linked','Linked transactions','number',true),t('expectedGross','Linked transactions expected gross','money'),m('gross','Provider gross'),m('fees','Provider fees'),m('deductions','Other deductions'),t('expectedNet','Linked transactions expected net','money'),m('actualNet','Actual settlement net'),m('variance','Source variance'),status,date],['organizationId','status'],'Provider settlements and linked expectations','Provider settlement date'),
 def('payouts','Payout Exceptions / Breaches','Financial','financial','Recorded transfer, evidence, partial balances, disputes and Organization responsibility.',[...context,m('transferred','Recorded transfer'),m('evidenced','Evidenced receipt'),m('outstanding','Payout outstanding'),t('dispute','Dispute / appeal'),t('restriction','Organization restriction'),status,date],dims,'7A payout projection and payout dispute records','Original payout target date'),
 def('recovery','Defaults & Recovery','Financial','financial','Private internal cross-Organization Recovery view. Principal first and oldest due rules remain unchanged.',[...context,m('principal','Original principal'),m('penalty','Accrued penalty'),m('recovered','Recovered aggregate'),m('principalOutstanding','Principal outstanding'),m('penaltyOutstanding','Penalty outstanding'),m('waived','Penalty waived'),m('outstanding','Total outstanding'),t('restriction','Restriction'),status,date],dims,'7A Recovery projection','Recovery opened date'),
 def('exits','Exit Settlement Breaches','Financial','financial','Organization liabilities to outgoing Members, separate from Member default.',[...context,m('due','Settlement due'),m('settled','Settled'),m('outstanding','Outstanding'),t('ageHours','Elapsed hours','number'),t('restriction','Organization restriction'),status,date],dims,'7A Exit Settlement projection and Operations links','Settlement due date; request date disclosed if unscheduled'),
 def('cases','Operations Cases','Operations','operations','Read-only case oversight using Module 5 state. Elapsed age is not an invented SLA breach.',[...context,t('reference','Case reference'),t('type','Case type'),t('module','Source module'),t('priority','Priority'),t('assignee','Assignee'),t('ageHours','Elapsed hours','number'),t('lastActivity','Last activity','date'),t('awaiting','Awaiting action'),status,date], [...dims,'type','module','priority','assignee','team','age'],'Module 5 projected cases and shared triage'),
 def('disputes','Disputes & Appeals','Operations','operations','Original decisions, independent appeals, evidence deadlines and exceptional reopenings.',[...context,t('reference','Dispute'),t('type','Dispute type'),m('amount','Disputed installment'),t('initialDecision','Initial decision'),t('appeal','Appeal status'),t('appealReviewer','Appeal reviewer'),t('deadline','Evidence deadlines'),t('reopened','Reopened'),status,date],dims,'Payout dispute processes and historical decisions'),
 def('activity','Material Internal Activity','Operations','operations','Material source decisions and historical authority. Access events appear only with Access Audit reporting permission.',[...context,t('actor','Historical actor'),t('type','Action'),t('target','Source target'),t('authority','Authority at decision'),date],['organizationId','type','actor','target'],'Source decision reviews; permission-filtered Access Audit'),
 def('access','Access Audit','Access & Security','access_audit','Readable access changes with preserved before/after state and historical actor.',[t('actor','Actor'),t('target','Target user / Role'),t('type','Action'),t('before','Before'),t('after','After'),t('privileged','Privileged'),t('reason','Reason'),date],['type','actor','target','privileged'],'Module 6 Access Audit'),
 def('security','Security Events','Access & Security','security','Simulated prototype events only; no claim about real authentication, tokens or production security.',[t('user','User'),t('type','Event'),t('context','Device / context'),t('result','Result'),t('actor','Administrative actor'),t('session','Session reference'),t('reason','Reason'),t('correlation','Linked Access Audit'),date],['type','actor','target','result'],'Module 6B simulated security events'),
 ...['Business Date Change History','Runtime Control Change History'].map((name,i)=>def(i===0?'business-date':'runtime-controls',name,'Configuration','platform','Immutable platform configuration source records.',[t('actor','Actor'),t('type','Action / control'),t('before','Prior mode/date or value'),t('after','New mode/date or value'),t('reason','Reason'),t('environment','Environment'),date],['actor','type'],'Module 8A configuration history','Actual wall-clock change timestamp')),
 def('process-runs','Scheduled Process Run History','Scheduled Processes','operations','Actual immutable process runs. Evaluation counts are Group/financial-world step evaluations, not unique financial records.',[t('reference','Run ID'),t('type','Process'),t('businessDate','Business Date'),t('trigger','Trigger'),t('actor','Actor'),date,t('completedAt','Actual end','date'),status,t('evaluated','Evaluated','number',true),t('changed','Changed','number',true),t('failures','Failed evaluations','number',true),t('retryOf','Retry of'),t('runs','Runs','number',true),t('successful','Completed with changes','number',true),t('noop','No changes','number',true),t('partial','Partial runs','number',true),t('failed','Failed runs','number',true)],['type','status','actor','businessDate','failedOnly'],'Module 8B run records','Actual run start timestamp; Business Date is a separate target filter'),
]
