import { DisplayDate } from '../design/foundation'
import {useState} from 'react'
import {useAccess} from './AccessContext'
import {hasPermission,canAccessModule} from './authorization'
import {securitySessions,securityEvents,lockedAccounts,securityOverview,changeSecurity,type SecurityAction} from './security'
const panel='rounded-xl bg-white border border-slate-200 p-5',control='rounded-lg border border-slate-300 px-3 py-2 text-sm',button='rounded-lg bg-blue-800 text-white px-4 py-2 text-sm disabled:opacity-40'
export function UserSecurity({userId}:{userId:string}){
 const a=useAccess(),s=a.session,u=a.state.users.find(u=>u.id===userId)
 if(!s||!u)return null
 const sessions=hasPermission(s,'security.sessions.view')?securitySessions(s).filter(r=>r.userId===userId):undefined
 const events=hasPermission(s,'security.events.view')?securityEvents(s).filter(e=>e.userId===userId).slice(0,3):undefined
 if(!sessions&&!events&&!hasPermission(s,'security.accounts.locked.view'))return null
 return <section className="mt-5 border-t pt-4"><h3 className="font-bold">Security · simulated internal account</h3>{hasPermission(s,'security.accounts.locked.view')&&<p className="text-sm mt-2">{u.security?.locked?'Security Locked':'Unlocked'} · Lifecycle: {u.status} · {u.security?.failedAttempts||0} historical failed attempts<br/>Last failure: {u.security?.lastFailureAt||'None'} · Last successful demo login: {u.security?.lastSuccessAt||'None'}</p>}{sessions&&<p className="text-sm mt-2">{sessions.filter(r=>r.status==='Active').length} active simulated sessions</p>}{events&&<ul className="text-sm mt-2 space-y-2">{events.map(e=><li key={e.id}>{e.type} · {<DisplayDate value={e.at}/>}</li>)}</ul>}</section>
}
export function SecurityWorkspace({initialView='Overview'}:{initialView?:string}){
 const a=useAccess(),[view,setView]=useState(initialView),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[userId,setUserId]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<{action:SecurityAction;version:string;actorId:string;summary:string}|null>(null)
 const s=a.session,can=(p:string)=>hasPermission(s,p)
 if(!s||!canAccessModule(s,'security'))return <p role="alert">Access denied. Security permission and an Active, unlocked internal user are required.</p>
 const views=[['Overview','security.overview.view'],['Sessions','security.sessions.view'],['Security Events','security.events.view'],['Locked Accounts','security.accounts.locked.view']].filter(([,p])=>can(p)).map(([v])=>v),active=views.includes(view)?view:views[0]
 const users=a.state.users,name=(id?:string)=>users.find(u=>u.id===id)?.name||id||'Role / platform',matches=(id:string,text:string)=>text.toLowerCase().includes(query.toLowerCase())&&(!userId||userId===id)
 const begin=(action:SecurityAction)=>{try{
  const copy={...s,access:structuredClone(s.access)};changeSecurity(copy,action,reason)
  const event=copy.access.history.at(-1)!,count=Array.isArray(event.after)?event.after.length:0
  const summary=action.type==='unlock'?`Clear the security lock for ${name(event.target)}. Lifecycle status and Roles remain unchanged; access still requires Active status and permissions.`:action.type==='revoke-all'?`This will terminate all active internal sessions for this user: ${name(event.target)} (${count} simulated sessions). Each record remains in history.`:`Revoke the selected simulated session for ${name(event.target)}. Other sessions remain unchanged.`
  setPreview({action,version:JSON.stringify(a.state),actorId:s.personaId,summary});setError('');setMessage('')
 }catch(e){setError((e as Error).message);setPreview(null)}}
 return <section className="space-y-5"><div className={panel}><h2 className="text-2xl font-bold">Security Administration</h2><p className="text-sm mt-2 text-slate-600">Simulated internal sessions and deterministic login examples. No real tokens, credential checks, MFA or device enforcement. Revocation changes these records; it does not invalidate a real login.</p></div><nav className="flex flex-wrap gap-3" aria-label="Security views">{views.map(v=><button aria-current={active===v?"page":undefined} key={v} className={active===v?button:control} onClick={()=>{setView(v);setStatus('');setPreview(null)}}>{v}</button>)}</nav>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-green-800">{message}</p>}
 {active==='Overview'&&<><div className="grid sm:grid-cols-3 gap-4">{Object.entries(securityOverview(s)).map(([key,count])=><article className={panel} key={key}><p className="text-sm">{({activeUsers:'Active internal users',activeSessions:'Active simulated sessions',locked:'Locked accounts',suspended:'Suspended users',revoked:'Revoked sessions',failedLogins:'Seeded failed logins'} as Record<string,string>)[key]}</p><p className="text-3xl font-bold mt-2">{count}</p></article>)}</div><p className="text-sm text-slate-600">Locked is a security condition. Suspended and Deactivated are separate lifecycle states. Login examples are dated 15 September 2026.</p></>}
 {active!=='Overview'&&<div className="flex flex-wrap gap-3"><input aria-label="Search security records" className={control} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, device or event"/><select aria-label="Security user filter" className={control} value={userId} onChange={e=>setUserId(e.target.value)}><option value="">All internal users</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select>{active==='Sessions'&&<select aria-label="Session status" className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All session states</option>{['Active','Expired','Revoked'].map(v=><option key={v}>{v}</option>)}</select>}{active==='Security Events'&&<select aria-label="Security event type" className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All event types</option>{[...new Set(securityEvents(s).map(e=>e.type))].map(type=><option key={type}>{type}</option>)}</select>}</div>}
 {(active==='Sessions'&&can('security.sessions.revoke')||active==='Locked Accounts'&&can('security.accounts.unlock'))&&<div className={panel}><label className="text-sm">Administrative reason (required)<textarea aria-label="Security action reason" className={control+' block w-full mt-2'} value={reason} onChange={e=>{setReason(e.target.value);setPreview(null)}}/></label><p className="text-xs mt-2">For your own sessions, ask another authorized administrator. This protects the current prototype demonstration.</p></div>}
 {preview&&<section className="rounded-xl border border-amber-300 bg-amber-50 p-5" aria-label="Security consequence preview"><h3 className="font-bold">Review security action</h3><p className="mt-2 text-sm">{preview.summary}</p><p className="text-sm mt-2">Reason: {reason}</p><div className="flex gap-3 mt-4"><button className={button} onClick={()=>{try{if(s.personaId!==preview.actorId)throw Error('Acting user changed. Preview again.');a.securityChange(preview.action,reason,preview.version);setPreview(null);setMessage('Simulated security state updated; audit history retained.');setError('')}catch(e){setError((e as Error).message);setPreview(null)}}}>Confirm simulated action</button><button className={control} onClick={()=>setPreview(null)}>Cancel</button></div></section>}
 {active==='Sessions'&&<div className="grid lg:grid-cols-2 gap-4">{securitySessions(s).filter(r=>(!status||r.status===status)&&matches(r.userId,name(r.userId)+' '+r.device+' '+r.id)).map(r=><article className={panel} key={r.id}><div className="flex justify-between gap-3"><h3 className="font-bold">{name(r.userId)}</h3><span className="text-sm">{r.status}</span></div><p className="text-sm mt-2">{r.device} · {r.trust}</p><p className="text-xs mt-2">{r.network} · {r.id}</p><p className="text-sm mt-3">Started: {<DisplayDate value={r.createdAt}/>}<br/>Last activity: {<DisplayDate value={r.lastActivityAt}/>}<br/>Expiry: {<DisplayDate value={r.expiresAt}/>}</p>{r.revokedAt&&<p className="text-sm mt-3">Revoked {<DisplayDate value={r.revokedAt}/>} by {name(r.revokedBy)} · {r.reason}<br/>Audit: {r.auditId||'Seeded historical example'}</p>}{r.status==='Active'&&can('security.sessions.revoke')&&<div className="flex flex-wrap gap-3 mt-4"><button className={control} onClick={()=>begin({type:'revoke',sessionId:r.id})}>Revoke session</button><button className={control} onClick={()=>begin({type:'revoke-all',userId:r.userId})}>Revoke all user sessions</button></div>}</article>)}</div>}
 {active==='Locked Accounts'&&<div className="grid lg:grid-cols-2 gap-4">{lockedAccounts(s).filter(u=>matches(u.id,u.name+' '+u.identifier)).map(u=><article key={u.id} className={panel}><h3 className="font-bold">{u.name} · Security Locked</h3><p className="text-sm mt-2">Lifecycle: {u.status}</p><p className="text-sm mt-2">{u.security?.lockReason}<br/>Locked: {<DisplayDate value={u.security?.lockedAt}/>}<br/>{u.security?.failedAttempts} failed attempts · Last failure: {<DisplayDate value={u.security?.lastFailureAt}/>}</p>{can('security.accounts.unlock')&&<button className={control+' mt-4'} onClick={()=>begin({type:'unlock',userId:u.id})}>Unlock security condition</button>}</article>)}</div>}
 {active==='Security Events'&&<ol className={panel+' divide-y'}>{securityEvents(s).filter(e=>(!status||e.type===status)&&matches(e.userId||'',name(e.userId)+' '+e.type+' '+e.reason)).map(e=><li key={e.id} className="py-4"><details><summary className="cursor-pointer text-sm font-semibold">{e.type} · {name(e.userId)} · {<DisplayDate value={e.at}/>}</summary><p className="text-sm mt-2">{e.result} · {e.reason}</p><p className="text-xs mt-2">{e.context} {e.sessionId&&'Session: '+e.sessionId}</p>{e.actor&&<p className="text-sm mt-2">Actor: {e.actor.name} · Authority at action: {e.actor.roles.map(r=>r.name).join(', ')}</p>}{e.accessChangeId&&<p className="text-xs mt-2">Linked access audit: {e.accessChangeId}. Before/after state is retained in Access Audit.</p>}</details></li>)}</ol>}
 </section>
}
