import { ScrollRegion, DisplayDate } from '../design/foundation'
﻿import { useState } from 'react'
import type { ThriftGroup, Cycle } from '../groups/model'
import { money } from '../rounds/model'
import { parsePaymentAmount } from '../payments/model'
import { penaltyBalance } from './balances'
export type WaivePenalty = (id:string,amount:number,reason:string)=>boolean
export function PenaltyLedgerPanel({group,cycle,memberId,onWaive}:{group:ThriftGroup;cycle:Cycle;memberId?:string;onWaive?:WaivePenalty}) {
 const [selected,setSelected]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('')
 const rows=(group.penalties?.accruals||[]).filter(a=>a.cycleId===cycle.id&&(!memberId||a.memberId===memberId))
 const defaults=(group.penalties?.defaults||[]).filter(d=>d.cycleId===cycle.id&&(!memberId||d.memberId===memberId))
 const totals=rows.reduce((n,a)=>{const b=penaltyBalance(group,a);return {accrued:n.accrued+b.accrued,waived:n.waived+b.waived,paid:n.paid+b.paid,outstanding:n.outstanding+b.outstanding}},{accrued:0,waived:0,paid:0,outstanding:0})
 return <section className="bg-white border border-[#E2E6F0] rounded-xl p-5 my-5">
  <h2 className="font-bold">Daily penalty ledger</h2>
  <p className="text-sm my-2">Accepted rate: {cycle.snapshot?.terms.dailyPenaltyRateBps ?? cycle.terms.dailyPenaltyRateBps ?? 0} bps/day. Simple, non-compounding; outstanding required principal only after grace. No charge on optional recipient contributions.</p>
  <p className="text-sm">Accrued {money(totals.accrued)} / waived {money(totals.waived)} / recovered {money(totals.paid)} / outstanding {money(totals.outstanding)}</p>
  {!rows.length?<p className="text-sm mt-3">No daily penalty accrual recorded.</p>:<details className="mt-3"><summary>View daily charges and reductions ({rows.length})</summary><ScrollRegion label="Daily penalty detail; scroll horizontally to inspect all columns"><table role="table" className={memberId ? "member-records-table w-full text-sm" : "owner-records-table w-full text-sm"}><thead role="rowgroup"><tr role="row">{['Date','Member / position','Principal basis','Rate','Accrued','Waived','Outstanding','Action'].map(label=><th scope="col" className="p-2 text-left" key={label}>{label}</th>)}</tr></thead><tbody role="rowgroup">{rows.map(a=>{const b=penaltyBalance(group,a);return <tr role="row" key={a.id}><td role="cell" data-label="Date" className="p-2">{a.accrualDate}</td><td role="cell" data-label="Member / position">{cycle.participants.find(p=>p.id===a.memberId)?.name||a.memberId} / {a.position}</td><td role="cell" data-label="Principal basis">{money(a.principalBasisMinor)}</td><td role="cell" data-label="Rate">{a.dailyRateBps} bps</td><td role="cell" data-label="Accrued">{money(a.amountMinor)}</td><td role="cell" data-label="Waived">{money(b.waived)}</td><td role="cell" data-label="Outstanding">{money(b.outstanding)}</td><td role="cell" data-label="Action">{onWaive&&b.outstanding>0&&<button type="button" className="text-blue-800 underline" onClick={()=>{setSelected(a.id);setAmount('');setReason('');setError('')}}>Reduce penalty</button>}</td></tr>})}</tbody></table></ScrollRegion></details>}
  {selected&&onWaive&&<form className="flex flex-wrap gap-3 mt-4" onSubmit={e=>{e.preventDefault();try{if(onWaive(selected,parsePaymentAmount(amount),reason)){setSelected('');setError('')}}catch(e){setError((e as Error).message)}}}><div className="w-full text-sm">{(()=>{const row=rows.find(a=>a.id===selected);if(!row)return null;const balance=penaltyBalance(group,row);return <p>Original accrued: {money(balance.accrued)} / already waived: {money(balance.waived)} / outstanding: {money(balance.outstanding)}. This records an audited reduction; it does not edit the original charge.</p>})()}</div><label>Reduction (NGN)<input className="border rounded p-2 block" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Reason<input className="border rounded p-2 block" value={reason} minLength={10} onChange={e=>setReason(e.target.value)} required/></label><button className="border rounded px-3" type="submit">Confirm audited reduction</button><button type="button" onClick={()=>setSelected('')}>Cancel</button>{error&&<p role="alert">{error}</p>}</form>}
  {(group.penalties?.waivers||[]).filter(w=>rows.some(a=>a.id===w.accrualId)).map(w=><p className="text-xs mt-2" key={w.id}>Reduction {money(w.amountMinor)} / {w.actor} / {w.at}: {w.reason}. Original accrual retained.</p>)}
  {defaults.map(d=><p className="text-sm mt-3" key={d.id}>{memberId ? "Post-Payout Default" : "POST_PAYOUT_DEFAULT"}: {cycle.participants.find(p=>p.id===d.memberId)?.name||d.memberId}; seven-day threshold <DisplayDate value={d.thresholdAt}/>; Recovery {group.lifecycle?.recoveries.find(r=>r.id===d.recoveryId)?.status||'open'}. Historical default retained.</p>)}
 </section>
}
